extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass

# ELEMENT MANIPULATION METHODS

func add_foreground_element(uniq_name:String, texture_path:String, pos:Vector2):
	# Adds a new foreground element to the scene.
	# A foreground element is anything in the foreground.
	# Usually a character.
	# All forground elements should have:
	# · A unique name
	# · A sprite texture
	# · A position
	# More attributes may be added during development.
	# This method relies on the fact that the name is in fact unique.
	# The name should be generated by the scene-making tool (as of yet 
	# undeveloped). If the name is not unique, it will result in undocumented
	# behaviour.
	var el = preload("res://scenes/visual_novel_scenes/foreground_element.tscn").instantiate()
	el.name = uniq_name;
	el.get_node("Sprite").texture = load(texture_path);
	el.position = pos;
	$ForegroundElements.add_child(el);


func remove_foreground_element(element_name:String):
	# Removes a foreground element object.
	# The element is identified by its unique name.
	# This name should be generated by the scene-making tool.
	# If a foreground element with such name doesn't exist in the current scene,
	# this will result in undocumented behaviour.
	var el = $ForegroundElements.get_node(element_name);
	el.queue_free();


func move_foreground_element(element_name:String, new_pos:Vector2, 
mode:String = "instant", duration:float = 1.0):
	# Moves a foreground element to a new position.
	# The type of motion is determined by the 'mode' argument:
	# · "instant" - The element moves instantly from place to place.
	#               In this case, the argument 'duration' is redundant.
	# · "linear" - The element moves linearly from place to place.
	#              It does so over the number of seconds specified by the
	#              argument 'duration'. 
	#              This movement is non-blocking, meaning several elements
	#              can move at the same time.
	# · "smooth" - The element accelerates for half the distance, and 
	#              deceelerates during the other half. The acceleration and
	#              deceleration are constant. The argument 'duration' still
	#              determines the duration of the movement.
	# More modes may be added in the future.
	var el = $ForegroundElements.get_node(element_name)
	if mode == "instant":
		el.position = new_pos
	elif mode == "linear":
		el.set_linear_movement(new_pos, duration)
	elif mode == "smooth":
		el.set_smooth_movement(new_pos, duration)
